export enum Permission {
    ALL = 'all',
    USER_READ = 'user:read',
    USER_EDIT = 'user:edit',
    ROLE_READ = 'role:read',
    ROLE_EDIT = 'role:edit',
    GUEST_READ = 'guest:read',
    GUEST_EDIT = 'guest:edit',
    BOOKING_READ = 'booking:read',
    BOOKING_EDIT = 'booking:edit',
    ROOM_READ = 'room:read',
    ROOM_EDIT = 'room:edit',
    CATEGORY_READ = 'category:read',
    CATEGORY_EDIT = 'category:edit',
    DOCUMENT_TYPE_READ = 'document-type:read',
    DOCUMENT_TYPE_EDIT = 'document-type:edit',
    IDENTITY_DOCUMENT_READ = 'identity-document:read',
    IDENTITY_DOCUMENT_EDIT = 'identity-document:edit',
    FOLIO_READ = 'folio:read',
    FOLIO_EDIT = 'folio:edit',
    SERVICE_READ = 'service:read',
    SERVICE_EDIT = 'service:edit',
    TEMPLATE_READ = 'template:read',
    TEMPLATE_EDIT = 'template:edit',
}
